create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;

postgres://
tahwmzsgvkvioa
:
ca6d563444e35548889e23133ed4cabb54ffa3ac979ba1c65ce2e5a0a0c8c33c
@
ec2-18-235-45-217.compute-1.amazonaws.com
:
5432
/
d1epa3u3p1ja3a